# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: AMRSKH.AngkorFetch
PackageVersion: "1.1.0"
InstallerType: zip
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/AMRSKH/angkorfetch/releases/download/v1.1.0/angkorfetch-windows-x86_64.zip
    InstallerSha256: bf9e7665eb055d20072e529e8f465d2045d82df97d7cbd78459d71b798fc27a3
    NestedInstallerType: portable
    NestedInstallerFiles:
      - RelativeFilePath: angkorfetch.exe
ManifestType: installer
ManifestVersion: 1.6.0
