# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: AMRSKH.AngkorFetch
PackageVersion: "1.1.2"
InstallerType: zip
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/AMRSKH/angkorfetch/releases/download/v1.1.2/angkorfetch-windows-x86_64.zip
    InstallerSha256: f00670f065efd75006cbd304b88fa283c275f95c74db232b4f3aa1a2d8260975
    NestedInstallerType: portable
    NestedInstallerFiles:
      - RelativeFilePath: angkorfetch.exe
ManifestType: installer
ManifestVersion: 1.6.0
